---
- name: SP download block
  block:
    - name: Set fact for temp toer dir
      ansible.builtin.set_fact:
        temporary_tower_dir: "/tmp/gts-ansible/temp_{{ tower_job_id }}"

    - name: Create temp tower dir for sched job
      ansible.builtin.file:
        path: "{{ temporary_tower_dir }}"
        state: directory
        mode: '1777'
        recurse: true

- name: Download file
  ansible.builtin.uri:
    url:
      "{{ sharepoint_site_url }}/_api/web/GetFileByServerRelativeUrl('{{ sharepoint_site_url | regex_replace('https?:.*?\\.com(\\/.*)', '\\1') }}/\
      {{ sharepoint_root_folder }}/{{ download_folder_name }}/{{ item }}')/$value"
    method: GET
    headers:
      Authorization: "Bearer {{ access_token }}"
      Content-Type: application/octet-stream
      X-RequestDigest: "{{ digest_code }}"
    dest: "{{ temporary_tower_dir }}/{{ item }}"
  register: download_result
  with_items: "{{ download_file_name }}"
  ignore_errors: true

- name: Initialize download_success
  ansible.builtin.set_fact:
    download_success: true

- name: Download results summary - When results are defined
  when:
    - download_result.results is defined
    - download_result.results | length > 0
  block:
    - name: Set download success files
      ansible.builtin.set_fact:
        sp_download_success_file: "{{ sp_download_success_file + [download_result.results[d_s_stat | int].item] }}"
      when: (download_result.results[d_s_stat | int].status == 200)
      with_sequence: start=0 count="{{ download_result.results | length }}"
      loop_control:
        loop_var: d_s_stat

    - name: Set download failed files
      ansible.builtin.set_fact:
        sp_download_failed_file: "{{ sp_download_failed_file + [download_result.results[d_f_stat | int].item] }}"
      when: not(download_result.results[d_f_stat | int].status == 200)
      with_sequence: start=0 count="{{ download_result.results | length }}"
      loop_control:
        loop_var: d_f_stat

    - name: Download Success (all files should be downladed)
      when: sp_download_failed_file | length == 0
      block:
        - name: Set download success
          ansible.builtin.set_fact:
            download_success: true

        - name: All files were downloaded successfully
          when: sp_download_success_file | length > 0
          block:
            - name: Recursively find files
              ansible.builtin.find:
                paths: "{{ temporary_tower_dir }}"
                recurse: true
              register: result

            - name: Add files to sp_downloaded_file
              ansible.builtin.set_fact:
                sp_downloaded_file: "{{ sp_downloaded_file + [item.path] }}"
              with_items: "{{ result.files }}"

            - name: SP download message
              ansible.builtin.debug:
                msg:
                  - "All given files were downloaded successfully"
                  - "Files: {{ sp_downloaded_file }}"
                  - "SPDSF: {{ sp_download_success_file }}"

            - name: Log lines to MS Teams - All files downloaded
              ansible.builtin.uri:
                url: "{{ webhook_url }}"
                body: "{{ message }}"
                body_format: json
                method: POST
              vars:
                message: "{{ lookup('template', '../templates/sharepoint_download_status.j2') }}"
                sharepoint_download_status_msg: "Success"
                sharepoint_downloaded_files: "{{ sp_download_success_file }}"
                sharepoint_download_failed_files: "NA"
                tower_job_suffix: "#/jobs/{{ tower_job_id }}"
                teams_summary: "{{ teams_notification_summary }}"
                teams_title: "{{ teams_notification_title }}"

        - name: No files were downloaded successfully
          when: not (sp_download_success_file | length > 0)
          block:
            - name: Set download success
              ansible.builtin.set_fact:
                download_success: false
                sp_download_success_file: []

            - name: SP download message
              ansible.builtin.debug:
                msg:
                  - "No files were downloaded successfully, Kindly Check the job log for more details."

            - name: Log lines to MS Teams - No files downloaded
              ansible.builtin.uri:
                url: "{{ webhook_url }}"
                body: "{{ message }}"
                body_format: json
                method: POST
              vars:
                message: "{{ lookup('template', '../templates/sharepoint_download_status.j2') }}"
                sharepoint_download_status_msg: "Failed"
                sharepoint_downloaded_files: "NA"
                sharepoint_download_failed_files: "{{ sp_download_failed_file }}"
                tower_job_suffix: "#/jobs/{{ tower_job_id }}"
                teams_summary: "{{ teams_notification_summary }}"
                teams_title: "{{ teams_notification_title }}"

    - name: Download Failed or Partially Failed (not all files were downladed)
      when: not (sp_download_failed_file | length == 0)
      block:
        - name: Set download success
          ansible.builtin.set_fact:
            download_success: false

        - name: Recursively find files
          ansible.builtin.find:
            paths: "{{ temporary_tower_dir }}"
            recurse: true
          register: result

        - name: Add files to sp_downloaded_file
          ansible.builtin.set_fact:
            sp_downloaded_file: "{{ sp_downloaded_file + [item.path] }}"
          with_items: "{{ result.files }}"

        - name: SP download message
          ansible.builtin.debug:
            msg:
              - "Some given files were downloaded partially"
              - "Files: {{ sp_downloaded_file }}"

        - name: Log lines to MS Teams - All files downloaded
          ansible.builtin.uri:
            url: "{{ webhook_url }}"
            body: "{{ message }}"
            body_format: json
            method: POST
          vars:
            message: "{{ lookup('template', '../templates/sharepoint_download_status.j2') }}"
            sharepoint_download_status_msg: "Partially Success"
            sharepoint_downloaded_files: "{{ sp_download_success_file }}"
            sharepoint_download_failed_files: "{{ sp_download_failed_file }}"
            tower_job_suffix: "#/jobs/{{ tower_job_id }}"
            teams_summary: "{{ teams_notification_summary }}"
            teams_title: "{{ teams_notification_title }}"

- name: Download results - When results are not defined
  when:
    - not (download_result.results is defined) or not (download_result.results | length > 0)
  block:
    - name: Set download success
      ansible.builtin.set_fact:
        download_success: false
        sp_download_success_file: []

    - name: SP download message
      ansible.builtin.debug:
        msg:
          - "Unable to get details on the download task."

    - name: Log lines to MS Teams - No files downloaded
      ansible.builtin.uri:
        url: "{{ webhook_url }}"
        body: "{{ message }}"
        body_format: json
        method: POST
      vars:
        message: "{{ lookup('template', '../templates/sharepoint_download_status.j2') }}"
        sharepoint_download_status_msg: "Failed"
        sharepoint_downloaded_files: "NA"
        sharepoint_download_failed_files: "NA"
        tower_job_suffix: "#/jobs/{{ tower_job_id }}"
        teams_summary: "{{ teams_notification_summary }}"
        teams_title: "{{ teams_notification_title }}"
