---

- name: Get www-authenticate http value from kyndryl.sharepoint.com
  ansible.builtin.uri:
    url: "https://{{ sharepoint_site_url | urlsplit('hostname') }}/_vti_bin/client.svc/"
    method: GET
    headers:
      Authorization: Bearer
    return_content: true
    status_code: 200,401
  register: response
  no_log: true

- name: Extract www-authenticate from response
  ansible.builtin.set_fact:
    www_authenticate: "{{ response.www_authenticate }}"
  no_log: true

- name: Extract Bearer Realm
  ansible.builtin.shell: |
    set -o pipefail &&
    echo {{ www_authenticate }} |
    sed 's/\\\\//g' |
    awk -F"," '{print $1}' |
    awk -F"=" '{print $2}' |
    tr -d '"'
  register: bearer_realm_response
  changed_when: false
  no_log: true

- name: Create bearer_realm variable
  ansible.builtin.set_fact:
    bearer_realm: "{{ bearer_realm_response.stdout }}"
  no_log: true

- name: Extract app_id
  ansible.builtin.shell: |
    set -o pipefail &&
    echo {{ www_authenticate }} |
    sed 's/\\\\//g' |
    awk -F"," '{print $2}' |
    awk -F"=" '{print $2}' |
    tr -d '"'
  register: app_id_response
  changed_when: false
  no_log: true

- name: Create app_id variable
  ansible.builtin.set_fact:
    app_id: "{{ app_id_response.stdout }}"

- name: Generate Sharepoint Access Token
  ansible.builtin.uri:
    url: "https://accounts.accesscontrol.windows.net/{{ bearer_realm }}/tokens/OAuth/2"
    method: POST
    headers:
      Content-Type: 'application/x-www-form-urlencoded'
    body_format: form-urlencoded
    body:
      grant_type: "client_credentials"
      client_id: "{{ sp_client_id }}@{{ bearer_realm }}"
      client_secret: "{{ sp_client_secret }}"
      resource: "{{ app_id }}/{{ sharepoint_site_url | urlsplit('hostname') }}@{{ bearer_realm }}"
    return_content: true
  register: response_token
  no_log: true

- name: Create Access Token variable
  ansible.builtin.set_fact:
    access_token: "{{ response_token.json.access_token }}"
  no_log: true

- name: Get Digest Sharepoint Value
  ansible.builtin.uri:
    url: "{{ sharepoint_site_url }}/_api/contextinfo"
    method: POST
    headers:
      Authorization: "Bearer {{ access_token }}"
      Content-Type: "application/json"
      Content-Length: "0"
    return_content: true
  register: response_digest
  failed_when: response_digest.status not in [200]
  no_log: true

- name: Extract Digest from response_digest
  ansible.builtin.set_fact:
    response_digest_section: "{{ response_digest.content | regex_findall('(?<=<d:FormDigestValue>)[^<]+') }}"
  no_log: true

- name: Split Digest from response_digest_section
  ansible.builtin.set_fact:
    digest_code: "{{ response_digest_section[0].split(',')[0] }}"
