---
- name: Delete file from SharePoint
  ansible.builtin.uri:
    url: "{{ sharepoint_site_url }}/_api/web/GetFileByServerRelativeUrl('{{ sharepoint_site_url | regex_replace('https?:.*?\\.com(\\/.*)', '\\1') }}/\
      {{ sharepoint_root_folder }}/{{ delete_folder_name }}/{{ item }}')"
    method: DELETE
    headers:
      Authorization: "Bearer {{ access_token }}"
      X-RequestDigest: "{{ digest_code }}"
  register: delete_result
  with_items: "{{ delete_file_name }}"
  ignore_errors: true

- name: Debug delete_result
  ansible.builtin.debug:
    var: delete_result

- name: Set fact fact for delete sucess
  ansible.builtin.set_fact:
    delete_success: "{{ delete_result.results | selectattr('status', 'in', [200]) | list | length == delete_result.results | length }}"
    delete_failed_file: "{{ delete_result.results | rejectattr('status', 'in', [200]) | map(attribute='item') | list }}"
    delete_success_file: "{{ delete_result.results | selectattr('status', 'in', [200]) | map(attribute='item') | list }}"
