---
- name: Verificar archivos en servidor Windows y subir reporte a SharePoint
  hosts: "{{ win_server }}"
  gather_facts: no

  vars:
    ansible_user: "{{ win_user }}"
    ansible_password: "{{ win_pass }}"
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
    win_path: \srvdfs01\APLICACIONES\BIG_DATA_MDMB_PRO\MDMAB\Lectures\
    checklist_code: CHK-0044
    sharepoint_site_url: https://kyndryl.sharepoint.com/teams/EnterpriseClientUnit-Ind.GenericTeam
    temp_dir: ./temp_report

  tasks:

    - name: Crear directorio temporal para reporte
      file:
        path: "{{ temp_dir }}"
        state: directory
      delegate_to: localhost

    - name: Obtener lista de archivos en servidor Windows
      win_find:
        path: "{{ win_path }}"
        file_type: file
      register: win_files

    - name: Generar reporte CSV
      ansible.builtin.template:
        src: report_template.csv.j2
        dest: "{{ temp_dir }}/{{ checklist_code }}_report.csv"
      vars:
        files: "{{ win_files.files }}"
      delegate_to: localhost

    - name: Subir reporte a SharePoint
      community.general.sharepoint_file:
        site_url: "{{ sharepoint_site_url }}"
        source: "{{ temp_dir }}/{{ checklist_code }}_report.csv"
        dest_folder: "Reportes/{{ checklist_code }}"
        username: "{{ sharepoint_user }}"
        password: "{{ sharepoint_pass }}"
      environment:
        REQUESTS_CA_BUNDLE: /etc/ssl/certs/ca-certificates.crt
      delegate_to: localhost  

    - name: Eliminar directorio temporal
      file:
        path: "{{ temp_dir }}"
        state: absent
      delegate_to: localhost
