---
# Playbook para verificaci贸n de archivos en Windows y carga a SharePoint
- name: Verificar archivos en Windows
  hosts: SRVMDCPRO03
  gather_facts: no
  vars:
    ansible_connection: winrm
    ansible_port: 5986
    ansible_winrm_transport: credssp
    ansible_winrm_server_cert_validation: ignore
    target_path: \\srvdfs01\APLICACIONES\BIG_DATA_MDMB_PRO\MDMAB\Lectures\
    csv_name: "resultados_checklist_{{ job_id }}.csv"
    
  tasks:
    - name: Buscar archivos en ruta especificada
      ansible.windows.win_find:
        paths: "{{ target_path }}"
        age: 0
      register: files_result

    - name: Generar estructura de resultados
      set_fact:
        checklist_results: |
          [
            {% for file in files_result.files %}
            ["CHK-0044", "Verificaci贸n de archivo {{ file.filename }}", "TC-{{ '%03d' % loop.index }}", 
            "Verificar existencia de {{ file.filename }} en {{ target_path }}", 
            "Archivo encontrado", "OK"]{% if not loop.last %},{% endif %}
            {% endfor %}
          ]
      when: files_result.files | length > 0

- name: Generar y cargar CSV
  hosts: localhost
  gather_facts: false
  vars:
    sharepoint_site_url: 'https://kyndryl.sharepoint.com/teams/EnterpriseClientUnit-Ind.GenericTeam'
    temp_path: "/tmp/ansible_checklist/{{ job_id }}/"
    
  tasks:
    - name: Crear directorio temporal
      ansible.builtin.file:
        path: "{{ temp_path }}"
        state: directory

    - name: Generar archivo CSV
      ansible.builtin.copy:
        dest: "{{ temp_path }}checklist_results.csv"
        content: |
          Checklist Code,Tarea,Task Code,Descripci贸n,Resultado,Estado
          {% for item in hostvars.SRVMDCPRO03.checklist_results | from_json %}
          {{ item|join(',') }}
          {% endfor %}
      delegate_to: localhost

    - name: Subir a SharePoint
      block:
        - name: Cargar archivo a SharePoint
          community.general.sharepoint:
            client_id: "{{ sp_client_id }}"
            client_secret: "{{ sp_client_secret }}"
            site_url: "{{ sharepoint_site_url }}"
            folder_path: "Documentos/Checklists/"
            file_path: "{{ temp_path }}checklist_results.csv"
            overwrite: yes
          register: upload_result

      rescue:
        - name: Manejar error en carga
          ansible.builtin.debug:
            msg: "Error subiendo archivo a SharePoint. C贸digo de error: {{ upload_result.status }}"

      always:
        - name: Limpiar archivos temporales
          ansible.builtin.file:
            path: "{{ temp_path }}"
            state: absent
          ignore_errors: yes
