---
- name: Verificar archivos en servidor Windows y subir reporte a SharePoint
  hosts: SRVMDCPRO03
  gather_facts: no

  vars:
    ansible_user: "{{ win_user }}"
    ansible_password: "{{ win_pass }}"
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
    win_path: \srvdfs01\APLICACIONES\BIG_DATA_MDMB_PRO\MDMAB\Lectures\
    checklist_code: CHK-0044
    sharepoint_site_url: https://kyndryl.sharepoint.com/teams/EnterpriseClientUnit-Ind.GenericTeam
    sp_client_id: 67b44fac-c6b7-42b3-b2c9-2c1a56266f5f
    sp_client_secret: ouV8Q~9xUZjQyOUFsSA3c6ngtrz.ZnIi1P03ubWW
    temp_dir: ./temp_report

  tasks:

    - name: Crear directorio temporal para reporte
      file:
        path: "{{ temp_dir }}"
        state: directory
      delegate_to: localhost

    - name: Obtener lista de archivos en servidor Windows
      win_find:
        path: "{{ win_path }}"
        file_type: file
      register: win_files

    - name: Generar reporte CSV
      ansible.builtin.template:
        src: report_template.csv.j2
        dest: "{{ temp_dir }}/{{ checklist_code }}_report.csv"
      vars:
        files: "{{ win_files.files }}"
      delegate_to: localhost
      
    - name: Leer contenido del reporte CSV
      slurp:
        src: "{{ temp_dir }}/{{ checklist_code }}_report.csv"
      register: report_content
      delegate_to: localhost

    - name: Subir reporte a SharePoint
      uri:
        url: "{{ sharepoint_site_url }}/_api/web/getfolderbyserverrelativeurl('Reportes/{{ checklist_code }}')/files/add(overwrite=true, url='{{ checklist_code }}_report.csv')"
        method: POST
        body: "{{ report_content['content'] | b64decode }}"
        body_format: raw
        headers:
          Authorization: "Bearer {{ sharepoint_access_token }}"
          Accept: "application/json;odata=verbose"
          Content-Type: "text/csv"
      delegate_to: localhost

    - name: Eliminar directorio temporal
      file:
        path: "{{ temp_dir }}"
        state: absent
      delegate_to: localhost
