---
# OBJETIVO: Este playbook (OS-WIN-ansible-role.CheckList.Averias) está diseñado para realizar una serie de tareas relacionadas con:
#            - Verificación de archivos en hosts Windows.
#            - Generación de un archivo CSV con resultados.
#            - Carga de resultados a SharePoint.

- name: PLAYBOOK CONTROL EXISTENCIA FICHEROS
  hosts: SRVMDCPRO03
  gather_facts: no
  vars:
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
    ansible_winrm_transport: ntlm
    ansible_port: 5985  # HTTP
    ansible_user: ansible
    ansible_password: Zaq12wsx
  tasks:
    - name: Probando conexión con win_ping
      ansible.windows.win_ping:  
    - name: CHECKLIST
      ansible.builtin.include_role:
        name: OS-WIN-ansible-role.CheckList.ControlExistenciaFicheros

- name: Prepare CSV output directory
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    job_id: "{{ tower_job_id | default(649) }}"
    tower_src_path: "/tmp/dashboard_out/{{ job_id }}"
  tasks:
    - name: Ensure output directory exists (Local task)
      ansible.builtin.file:
        path: "{{ tower_src_path }}"
        state: directory
        mode: '0755'

- name: Process results and call CSV Dashboard role
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    checklist_code: 'CHK-0044'
    job_id: "{{ tower_job_id | default(649) }}"
    tower_src_path: "/tmp/dashboard_out/{{ job_id }}"
  tasks:
    - name: Initialize all_host_results
      ansible.builtin.set_fact:
        all_host_results: []
     
    - name: Set windows_hosts fact
      ansible.builtin.set_fact:
        windows_hosts: "{{ [inventory_hostname] if inventory_hostname == 'SRVMDCPRO03' else groups['windows']|default([]) }}"
     
    - name: Collect results from Windows hosts
      ansible.builtin.set_fact:
        all_host_results: "{{ all_host_results + hostvars[item]['arr_results']|default([]) }}"
      loop: "{{ windows_hosts|default([]) }}"
      when: 
        - hostvars[item] is defined
        - hostvars[item]['arr_results'] is defined
    
    - name: Create placeholder file if no results
      ansible.builtin.copy:
        content: "No results found in this execution"
        dest: "{{ tower_src_path }}/no_results.txt"
      when: all_host_results | length == 0
        
    - name: Call OS-LINUX-ansible-role.CSV.Dashboard for each result
      include_role:
        name: OS-LINUX-ansible-role.CSV.Dashboard
      vars:
        fase: "create"
        checklist_code: "{{ item[0] }}"
        task_name: "{{ item[1] }}"
        task_code: "{{ item[2] }}"
        task_description: "{{ item[3] }}"
        task_result_description: "{{ item[4] }}"
        task_result: "{{ item[5] }}"
      loop: "{{ all_host_results }}"
      when: all_host_results | length > 0

- name: Upload Files to SharePoint
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    job_id: "{{ tower_job_id | default(626) }}"
    create_folder_in_sp: false
    create_custom_folder: false 
    custom_folder_name: "{{ gsma_code | default('SYN') }}"
    upload_to_custom_folder: false
    create_subfolder_in_sp: false
    subfolder_name: "Checklist"
    upload_to_subfolder: true
    sharepoint_root_folder: 'at_role'
    sharepoint_site_url: 'https://kyndryl.sharepoint.com/teams/EnterpriseClientUnit-Ind.GenericTeam'
    sp_teams_notification: false
    tower_src_path: "/tmp/dashboard_out/{{ job_id }}"
 
  tasks:
    - name: Check SharePoint upload prerequisites
      block:
        - name: Verify upload directory
          ansible.builtin.stat:
            path: "{{ tower_src_path }}"
          register: upload_dir
          failed_when: not upload_dir.stat.exists

        - name: List files in directory
          ansible.builtin.shell: 
            cmd: "ls {{ tower_src_path }}"
          register: file_list
          changed_when: false
          failed_when: file_list.stdout_lines | length == 0

        - name: Debug directory contents
          ansible.builtin.debug:
            var: file_list.stdout_lines

        - name: Upload to SharePoint
          block:
            - name: Include SharePoint upload role
              ansible.builtin.include_role:
                name: ansible_role_sharepoint_upload
              vars:
                sp_client_id: "{{ username }}"
                sp_client_secret: "{{ key }}"
          rescue:
            - name: Log SharePoint upload failure
              ansible.builtin.debug:
                msg: "Error al subir archivos a SharePoint"

            - name: Create placeholder for upload issue
              ansible.builtin.copy:
                content: "SharePoint upload failed"
                dest: "{{ tower_src_path }}/upload_error.txt"

      rescue:
        - name: Handle directory or file listing errors
          ansible.builtin.debug:
            msg: "No se encontraron archivos para subir o el directorio no existe"

        - name: Create default placeholder
          ansible.builtin.copy:
            content: "No files available for upload"
            dest: "{{ tower_src_path }}/placeholder.txt"

      always:
        - name: Final upload status log
          ansible.builtin.debug:
            msg: "Proceso de subida a SharePoint completado"
