---
# OBJETIVO: Este playbook (OS-WIN-ansible-role.CheckList.Averias) está diseñado para realizar una serie de tareas relacionadas con:
#            - Verificación de archivos en hosts Windows.
#            - Generación de un archivo CSV con resultados.
#            - Carga de resultados a SharePoint.
#
# ESCENARIO: Entorno de ejecución controlado desde la máquina de salto de Agbar (Aigües de Barcelona).
#
# REQUISITOS: 
#     - Ejecución desde el servidor de salto corporativo de Aigües de Barcelona.
#     - Conexión a hosts Windows con credenciales adecuadas.
#     - Acceso al storage blob de Azure y a SharePoint.
#
# INVENTARIO-CONFIG:
#     Grupos:
#         - <tricode>_grp_INRA_AZURE  # Reemplazar <tricode> con el identificador del entorno
#     Group_vars:
#         - azure_url: "https://mdmabpro01sa.file.core.windows.net/sicab/MDMAB/Lectures/"   ## URL fija del storage de Azure  (string)
#         - file_path: "\\srvdfs01\APLICACIONES\BIG_DATA_MDMB_PRO\MDMAB\Lectures\"          ## Share del servidor local donde buscar el fichero inicialmente (string)
#         - sharepoint_site_url: "https://kyndryl.sharepoint.com/teams/EnterpriseClientUnit-Ind.GenericTeam" ## URL del sharepoint  (string)
#         - server_hostname: srvtsadmpro01.agbar.ga.local         ## servidor Windows que se está gestionando (string)
#         - tower_src_path: "/tmp/dashboard_out/{{ tower_job_id }}" ## Define la ruta local (en el nodo de control) donde se almacenan los archivos generados por el playbook (ej: CSV de resultados) (string)
#
# CREDENCIALES-REQs:  # Valores sensibles (usar Ansible Vault)
#     - sp_client_id: "<client_id_sharepoint>"           # ID de cliente para autenticación en SharePoint (string)
#     - sp_client_secret: "<client_secret_sharepoint>"   # Secret para autenticación (string)
#     - sas_url: "<cadena_SAS_azure>"                    # Cadena SAS para acceso al blob storage de Azure (string)
#
# INPUT-VARs-REQs:    # Variables obligatorias pasadas en tiempo de ejecución
#     - job_id:  # ID único de ejecución (integer)
#
# INPUT-VARs-OPTs:    # Variables opcionales con valores por defecto
#     - delegate_launch_node_linux: "localhost"  # Nodo de ejecución para tareas Linux
#     - gsma_code: "SYN"  # Código GSMA por defecto Se usa como nombre de carpeta principal dentro de la estructura de SharePoint (string) 
#
# NOTAS:
#     - Las credenciales (sp_client_id, sp_client_secret, sas_url) deben encriptarse con Ansible Vault.
#     - La ruta `file_path` puede modificarse desde el inventario si es necesario.
#     - Para la ejecucion de este playbook llama a dos roles OS-LINUX-ansible-role.CSV.Dashboard  y role_sharepoint_upload 
#
#
#
- name: PLAYBOOK CONTROL EXISTENCIA FICHEROS
  hosts: SRVMDCPRO03
  gather_facts: no
  vars:
    ansible_connection: winrm
    ansible_port: 5986
    ansible_winrm_server_cert_validation: ignore
    ansible_winrm_transport: ntlm
    ansible_port: 5985  # HTTP
    ansible_user: ansible
    ansible_password: Zaq12wsx
  tasks:
    - name: Probando conexión con win_ping
      ansible.windows.win_ping:  
  tasks:   
    - name: CHECKLIST
      ansible.builtin.include_role:
        name: OS-WIN-ansible-role.CheckList.ControlExistenciaFicheros

- name: Process results and call CSV Dashboard role
  hosts: "{{ delegate_launch_node_linux if delegate_launch_node_linux | default('') else 'localhost' }}"
  gather_facts: yes
  vars:
    checklist_code: 'CHK-0044'
  tasks:
    - name: Initialize all_host_results
      set_fact:
        all_host_results: []        
     #Luego, recopila los resultados de todos los hosts en Windows
    - name: Collect results from Windows hosts
      set_fact:
        all_host_results: "{{ all_host_results + hostvars[item]['arr_results']|default([]) }}"
      loop: "{{ groups['windows']|default([]) }}"
      when: hostvars[item] is defined and hostvars[item]['arr_results'] is defined
        
    - name: Call OS-LINUX-ansible-role.CSV.Dashboard for each result
      include_role:
        name: OS-LINUX-ansible-role.CSV.Dashboard
      vars:
        fase: "create"
        checklist_code: "{{ item[0] }}"
        task_name: "{{ item[1] }}"
        task_code: "{{ item[2] }}"
        task_description: "{{ item[3] }}"
        task_result_description: "{{ item[4] }}"
        task_result: "{{ item[5] }}"
      loop: "{{ all_host_results }}"
    - name: Set all host results fact
      set_fact:
        all_host_results: "{{ all_host_results|default([]) + hostvars[item]['arr_results']|default([]) }}"
      loop: "{{ groups['windows']|default([]) }}"
      when: hostvars[item]['arr_results'] is defined 

- name: Upload Files to Sharepoint
  #hosts: SRVMDCPRO03
  hosts: "{{ delegate_launch_node_linux if delegate_launch_node_linux | default('') else 'localhost' }}"
  gather_facts: true
  #gather_facts: no
  vars:
    job_id: 1
    create_folder_in_sp: false
    create_custom_folder:  false ##true
    custom_folder_name: "{{ gsma_code }}"
    upload_to_custom_folder: false
    create_subfolder_in_sp: false  ##true
    subfolder_name: "Checklist"
    upload_to_subfolder: 1  ##true
    sharepoint_root_folder: 'at_role'
    sharepoint_site_url: 'https://kyndryl.sharepoint.com/teams/EnterpriseClientUnit-Ind.GenericTeam'  # Usar variable de inventario
    sp_teams_notification: 0 ##false
    tower_src_path: "/tmp/dashboard_out/{{ job_id }}"
 
  tasks:
    - name: Upload to sharepoint
      ansible.builtin.include_role:
        name: ansible_role_sharepoint_upload
      #register: sp_upload_result
      vars:
        sp_client_id: "{{ username }}"
        sp_client_secret: "{{ key }}"

    - name: Delete Output Files
      block:
        - name: Remove files using shell command
          ansible.builtin.shell: 
            cmd: rm -rf "{{ tower_src_path }}"
          when: 
             - sp_upload_result is defined 
             - sp_upload_result is not none 
             - sp_upload_result.failed | default(false) == false
      rescue:
        - name: Fallback removal method
          ansible.builtin.file:
            path: "/tmp/dashboard_out/{{ job_id }}"
            state: absent
