---
# OBJETIVO: Este playbook está diseñado para realizar una serie de tareas relacionadas con:
#            - Verificación de archivos en hosts Windows.
#            - Generación de un archivo CSV con resultados.
#            - Guardar resultados en AWX.

- name: PLAYBOOK CONTROL EXISTENCIA FICHEROS
  hosts: SRVMDCPRO03
  gather_facts: no
  vars:
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
    ansible_winrm_transport: ntlm
    ansible_port: 5986  # HTTPS (cambiado a 5986 para conexión segura)
    ansible_user: ansible
    ansible_password: Zaq12wsx
  tasks:
    - name: Probando conexión con win_ping
      ansible.windows.win_ping:  
    - name: CHECKLIST
      ansible.builtin.include_role:
        name: OS-WIN-ansible-role.CheckList.ControlExistenciaFicheros

- name: Prepare CSV output directory
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    job_id: "{{ tower_job_id | default(649) }}"
    csv_dir: "/tmp/job"
  tasks:
    - name: Ensure output directory exists (Local task)
      ansible.builtin.file:
        path: "{{ csv_dir }}"
        state: directory
        mode: '0755'

- name: Process results and generate CSV file
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    checklist_code: 'CHK-0044'
    job_id: "{{ tower_job_id | default(649) }}"
    csv_dir: "/tmp/job"
    csv_file: "{{ csv_dir }}/control_existencia_ficheros_{{ job_id }}.csv"
  tasks:
    - name: Initialize all_host_results
      ansible.builtin.set_fact:
        all_host_results: []
     
    - name: Set windows_hosts fact
      ansible.builtin.set_fact:
        windows_hosts: "{{ [inventory_hostname] if inventory_hostname == 'SRVMDCPRO03' else groups['windows']|default([]) }}"
     
    - name: Collect results from Windows hosts
      ansible.builtin.set_fact:
        all_host_results: "{{ all_host_results + hostvars[item]['arr_results']|default([]) }}"
      loop: "{{ windows_hosts|default([]) }}"
      when: 
        - hostvars[item] is defined
        - hostvars[item]['arr_results'] is defined
    
    - name: Create placeholder file if no results
      ansible.builtin.copy:
        content: "No results found in this execution"
        dest: "{{ csv_dir }}/no_results_{{ job_id }}.txt"
      when: all_host_results | length == 0
        
    - name: Generate CSV file with headers
      ansible.builtin.copy:
        content: "checklist_code,task_name,task_code,task_description,task_result_description,task_result\n"
        dest: "{{ csv_file }}"
      when: all_host_results | length > 0
        
    - name: Append results to CSV file
      ansible.builtin.lineinfile:
        path: "{{ csv_file }}"
        line: "{{ item[0] }},{{ item[1] }},{{ item[2] }},{{ item[3] }},{{ item[4] }},{{ item[5] }}"
      loop: "{{ all_host_results }}"
      when: all_host_results | length > 0

    - name: Display CSV file location
      ansible.builtin.debug:
        msg: "CSV file has been generated at {{ csv_file }}"
      when: all_host_results | length > 0
