---
- name: Check Avaries Interiores
  ansible.builtin.include_tasks: check_proc_interiors.yml

- name: Iniciando Tareas
  block:
    - name: Revisando ficheros 
      ansible.windows.win_find:
        paths:
          - 'D:\AVARIES\Response\01\'
          - 'D:\AVARIES\Response\01\OK'
          - 'D:\AVARIES\Response\02\'
          - 'D:\AVARIES\Response\02\OK'
          - 'D:\AVARIES\Response\03\'
          - 'D:\AVARIES\Response\03\OK'
          - 'D:\AVARIES\Response\05\'
          - 'D:\AVARIES\Response\05\OK'
          - 'D:\AVARIES\Response\06\'
          - 'D:\AVARIES\Response\06\OK'
        recurse: no
        use_regex: yes
        patterns: '^(?!.*AnulaErr\.xml$).*\.xml$'
      register: xml_files

    - name: Notificar si no se encuentran archivos XML
      ansible.builtin.debug:
        msg: "No se encontraron archivos XML en el directorio especificado."
      when: xml_files.matched == 0

    - name: Stop Avaries Interiors
      ansible.builtin.include_tasks: win_proc_exec.yml
      vars:
        script_path: 'D:\Parada y Arranque de Servicios\servicestop.bat'

    - name: Rename XML files to XML.old
      ansible.windows.win_command:
        cmd: powershell -Command "Rename-Item -Path '{{ item.path }}' -NewName '{{ item.path }}.old'"
      loop: "{{ xml_files.files }}"
      when: xml_files.matched > 0


    - name: Start Avaries Interiors
      ansible.builtin.include_tasks: win_proc_exec.yml
      vars:
        script_path: 'D:\Parada y Arranque de Servicios\service.bat'
    
    - name: Rename XML.OLD files to XML
      ansible.windows.win_command:
        cmd: powershell -Command "Rename-Item -Path '{{ item.path }}.old' '{{ item.path }}'"
      loop: "{{ xml_files.files }}"
      when: xml_files.matched > 0

    - name: Check Avaries Processos Interiors
      ansible.builtin.include_tasks: check_proc_interiors.yml

    - name: Pause for 30 seconds
      ansible.builtin.pause:
        seconds: 30

    - name: Revisamos si se procesan los ficheros en de averias exteriores
      ansible.windows.win_find:
        paths:
          - 'D:\AVARIES\Response\01\'
          - 'D:\AVARIES\Response\01\OK'
          - 'D:\AVARIES\Response\02\'
          - 'D:\AVARIES\Response\02\OK'
          - 'D:\AVARIES\Response\03\'
          - 'D:\AVARIES\Response\03\OK'
          - 'D:\AVARIES\Response\05\'
          - 'D:\AVARIES\Response\05\OK'
          - 'D:\AVARIES\Response\06\'
          - 'D:\AVARIES\Response\06\OK'
        recurse: no
        patterns: "*.xml"
      register: actual_xml_files

    - name: DEBUG files
      ansible.builtin.debug:
        msg: "ACTUALES: {{ actual_xml_files.matched }} ANTIGUOS: {{ xml_files.matched }}"

    - name: ERROR en la validacion procesamiento de ficheros
      ansible.builtin.fail:
        msg: "Los ficheros NO se estan procesando o estan tardando mas de lo habitual"
      when: actual_xml_files.matched >= xml_files.matched and xml_files.matched > 0
  when: not procs_ok
