#SPDX-License-Identifier: MIT-0
---
# defaults file for syn-control-existencia-ficheros
# Variables de conrtol
file1_ok: false
fase: "create"
azure_check: false

# Variables del playbook
checklist_code: 'CHK-0044'
client_code: 'SYN'
file_path: '\\srvdfs01\APLICACIONES\BIG_DATA_MDMB_PRO\MDMAB\Lectures\' #No olvidar la "\" al final!

#Dividir el link del SAS en 2 partes, 1 (azure_url) desde https hasta "?" (NO INCLUIDO)
azure_url: "https://mdmabpro01sa.file.core.windows.net/sicab/MDMAB/Lectures/"
# 2 (sas_url) copiar desde el "?" hasta el final "?" incluido.
sas_url: "?example" 
